### ISSUE TITLE
Choose color for alpha in previews

### ISSUE THREAD

**Issue by mkolar** [pypeclub/pype#1003]
<div> Freshdesk Ticket ID: <a href="https://pype.freshdesk.com/a/tickets/276">276</a></div>

<div>We often use black lines in out animation so having a black bg to represent alpha will not be useable. <span style="">Therefore it would be great to render alpha as white. This can be done across all kinds of shots.</span>
</div>
</div>

**Comment by mkolar** [comment]
<div>Agent Milan Kolar linked Freshdesk ticket <a href="https://pype.freshdesk.com/a/tickets/276">276</a> for this issue.</div>

**Comment by iLLiCiTiT** [comment]
I have and idea how to achieve that but it is possible I will break some behavior connected with rescaling, letter box and others (related issue https://github.com/pypeclub/pype/issues/991). Reason is that I don't know what is expected result in specific situations and this would add another situation...

## How I would do it at this moment:
- output definition from settings (presets) would have `bg_color` where HEX color can be stored
- this color will be used only if is entered, valid and input file has extention that potentialy may have ability to use different background (`exr`, `png`, `dpx`)
- add at the end of ffmpeg video filters these filters `split=2[bg][fg];[bg]drawbox=c={color}@1:replace=1:t=fill[bg];[bg][fg]overlay=format=auto`
- but not sure what is expected output if input is rescaled during processing, letterboxes are added, etc.

**Comment by iLLiCiTiT** [comment]
For Pype 2 it is (will be) resolved with https://github.com/pypeclub/pype/pull/1088 .

In Pype 3 we should think about better solution how and where define bg color and where and when use it. BG color is not just issue of review extraction but also thumbnails. Thumbnails creation is now a little bit mess.
- thumbnails are not created from result of extract review so setting bg color in extract review won't affect thumbnails
- at the same time thumbnails may be created without extract review (this is primarily issue of standalone publisher)
    - should be able use same bg color? how to pass the color or where to set it and how to define if should be used?
    - initial idea was to set it in output definitions of extract review plugin but that would affect only the plugin and is not usable in other situations
- thumbnail probably should not be a representation
    - was ever used as representation e.g. for loading?
- should be possible to have thumbnail for each publishing instance even if `review` is not created
