### ISSUE TITLE
Acre: appending or overriding env variables

### ISSUE THREAD

**Issue by antirotor** [pypeclub/pype#101]
**Describe the bug**
There are cases when environment variable set via acre is overidden by new value - and expected behavior is that value should be appended, like in `PATH`. And then there is variable expected to be overriden and value is appended there. We need to test those cases to ensure correct behavior.

**To Reproduce**
set `PATH` initialy to:
```sh
set PATH="/bar/baz"
```
and then in tool json file:
```javascript
{
    "PATH": "/foo/bar"
}
```
observed behavior is:
```sh
echo $PATH
/foo/bar
```
This can be overcome in json like:

```javascript
{
    "PATH": [
        "{PATH}",
        "/foo/bar"
    ]
}
```

But then we have:

```sh
set FOO="//foo/bar"
```

and in `global.json`:
```javascript
{
    "FOO": "//baz/goo"
}
```

and this will result in:

```sh
echo $FOO
//foo/bar;//baz/goo
```

**Comment by antirotor** [comment]
This seems to be identified as bug in acre. It works on windows, but on other platforms `acre.append()` doesn't respect platform path separator and is using `;` directly.

**Comment by BigRoy** [comment]
Interesting. Would be to good to see a PR to `acre`.

**Comment by antirotor** [comment]
I've created PR of it - BigRoy/acre#6

**Comment by antirotor** [comment]
This was misunderstanding how acre work internally and how we are treating environment during startup.
