### ISSUE TITLE
Disable NextTaskUpdate event.

### ISSUE THREAD

**Issue by tokejepsen** [pypeclub/pype#1056]
**Goal**

Need a setting for disabling the "NextTaskUpdate" event plugin; https://github.com/pypeclub/pype/blob/2.x/main/pype/modules/ftrack/events/event_next_task_update.py

**Comment by iLLiCiTiT** [comment]
In Pype 2 go to `~/pype-config/presets/ftrack/plugins/server.json` add there:
```json
{
    "NextTaskUpdate": {
        "ignore_me": true
    }
}
```
And restart Processor on ftrack event server.

**Comment by tokejepsen** [comment]
Awesome, that works!
Will this be available in the new settings?

**Comment by iLLiCiTiT** [comment]
> Will this be available in the new settings?

It is more dynamic in Pype 3. You can turn it on/off per project without restarting event server.

**Comment by mkolar** [comment]
sneak peak 
![image](https://user-images.githubusercontent.com/3333008/109034273-c627d200-76c7-11eb-9b6f-4108a0c1b710.png)
