### ISSUE TITLE
Nuke: AvalonTab as default for write node

### ISSUE THREAD

**Issue by 64qam** [pypeclub/pype#1089]
AvalonTab should be opened as a default tab in Properties window of a write node. Nowadays the Deadline tab is set as default and it causes that users do not see the possibilities of rendering at first sight. 

![image](https://user-images.githubusercontent.com/26925793/109975413-e6284880-7cfa-11eb-8ddb-fbe2fe1d707e.png)

**Comment by jezscha** [comment]
Unfortunatelly this is platform related bug. All works fine in windows but Linux is opening the lastly created tab Deadline. 

Two ways of solving it. 

1. Create Deadline tab as first and AvalonTab as second. This should be done only if linux and also perhaps MacOS
2. Merge Deadline tab into AvalonTab as options at bottom with Deadline named Splitter

Or do you have anyone some other suggestions? @mkolar @tokejepsen ?

**Comment by tokejepsen** [comment]
This is happening here on Windows as well.

Not actually entirely sure why the Deadline tab is separate to the Avalon tab. As you say with a splitter and possible a label (of some kind), it could all be on one tab.

**Comment by jezscha** [comment]
> This is happening here on Windows as well.
> 
> Not actually entirely sure why the Deadline tab is separate to the Avalon tab. As you say with a splitter and possible a label (of some kind), it could all be on one tab.

I see. I work perfect on my workstation, but anyway I found a solution to this and we can preserve those two tabs separated.
