### ISSUE TITLE
Burnin Script does not have configurable CRF

### ISSUE THREAD

**Issue by tokejepsen** [pypeclub/pype#110]
**Describe the bug**
The [burnin script](https://github.com/pypeclub/pype/blob/develop/pype/scripts/otio_burnin.py) does not have any way of configuring the quality (CRF)

I could be wrong about this, but this was an issue in our outdated pipeline, where we needed the quality to be crf 10 but the burnin script has no quality control.

**Comment by mkolar** [comment]
burnin script should always copy whatever input goes into it and not change it. We've just actually re-written most of this to be much more flexible and robust, but I believe this particular behaviour we've kept.

Do you see a change in quality before and after burnins?

**Comment by tokejepsen** [comment]
Sorry, have tested this properly and it works as intended.

The quality setting on the preset of the review is works to get the quality needed for the client review.
