### ISSUE TITLE
DWAA Support

### ISSUE THREAD

**Issue by tokejepsen** [pypeclub/pype#111]
**Goal**
Support DWAA renders.

**Implementation**
I submitted a solution last year to support DWAA compression. The issue is when extracting the review,  that ffmpeg dont recognize DWAA compressed images.

I might be missing something, but I dont see the solution in the code so wanna make sure pype supports it.

Implementation wise it ended up being a library method for ensuring ffmpeg compatibility, that requires imagemagick;
```python
def ensure_ffmpeg_compat(path, start_frame=None, end_frame=None):
    """Checks the file path for ffmpeg compatible compression.

    Requires Image Magick.

    Args:
        path (str): file path.
        start_frame (int): start frame of a sequence.
        end_frame (int): end frame of a sequence.

    Returns:
        str: file path either of orignal or conversion.
    """

    if path.endswith(".exr"):
        args = ["magick", "identify", "-format", "\"%[compression]\""]

        if start_frame is None:
            args.append(path)
        else:
            args.append(path % start_frame)

        output = _subprocess(args)

        if "DWAA" in str(output) or "DWAB" in str(output):
            # Suffixing file name with "_temp" for later clean up.
            output_path = path.replace(
                os.path.splitext(path)[1], "_temp" + os.path.splitext(path)[1]
            )

            args = ["magick", "convert", "-background", "rgba(0, 0, 0, 0)"]

            if start_frame is None and end_frame is None:
                args.append(path)
            else:
                args.append("{}[{}-{}]".format(path, start_frame, end_frame))

            # Using no compression for speed and the files should be deleted
            # once used.
            args.extend(["-compress", "None"])

            if start_frame is not None:
                args.extend(["-scene", str(start_frame)])

            args.append(output_path)

            _subprocess(args)

            return output_path

    return path
```

**Comment by antirotor** [comment]
> I might be missing something, but I dont see the solution in the code so wanna make sure pype supports it.

I think we decided along the way that we'll use [OIIO](https://github.com/OpenImageIO/oiio) for it as we need it nevertheless, so as not to add another dependency like Image Magic. But @iLLiCiTiT  will know more.

**Comment by mkolar** [comment]
Yeah that was the reason, however we never actually got around to doing it. Problem with ImageMagick is that it is windows only if you want to keep easy installation. 

However I'm open to making a new PR with this as a temporary windows only support for DWAA.

**Comment by iLLiCiTiT** [comment]
OIIO tool I've build for windows should be enough for basic DWAA support, so we need static oiio tool for linux (and darwin?) - I can play with making that tomorrow (Holiday activity :) ), create basic python script which just convert exrs to pngs and it's ready to implement... That might be enough for the first version, until we'll build oiio tool with all wanted features.

**Comment by antirotor** [comment]
This also concerns support for mutlipart/multichannel exrs and possibly lot of other stuff oiio supports and ffmpeg not. Currenly 
 even Thumbnail extraction from multichannel/dwaa is impossible. If we find out we have ffmpeg incompatible exr, we should convert image(s) using OIIO to something ffmpeg undesrstand, feed it to extract jpg/review plugins and then delete it.

**Comment by mkolar** [comment]
Due to other client requirements we've already added OIIO into pype, so making this happen is trivial now. Just need to swap the imagemagick with oiio in the code pretty much.
