### ISSUE TITLE
Site Sync - add site information and buttons to loader

### ISSUE THREAD

**Issue by mkolar** [pypeclub/pype#1121]
Site sync is now ready to be beta tested, however, we are missing GUI tools to pull data from a remote site to local storage.

We need to figure out a clear way of displaying whether a version and it's representations are localised and available on the remote. Plus give a way of pull particular version or it's individual representations. 

I reckon we could use the area on the right to display most of this, while possibly also giving quicker access to representations

![image](https://user-images.githubusercontent.com/3333008/110943565-a6d1ab80-833b-11eb-9c76-decc1f9b5d35.png)

**Comment by tokejepsen** [comment]
This reminds me of @mottosso first journal of what became Avalon; https://mindbender-studio.github.io/journal/p/week-9/#selective-sync

**Comment by mottosso** [comment]
Feels like ages ago, barely recognise any of that xDD

**Comment by mkolar** [comment]
I knew I saw that somewhere. wanted to link it here, but couldn't for the life of me remember where it was :).

Yeah it's similar but a bit more ...finished  at this point :).

We'll be release detailed info on implementation soon. Essentially we can define `active` and `remote` sites on each pype instance that is running which can be anything from disk, to cloud storage. Publisher then publishes to active and can tag the files for syncing to remote site. Pype tray then takes care of the sync in the background similar to google drive. 

Backend is all there now and running quite nicely, but it needs some frontend work for it to be production testable. Sneak peak...
![Uploading image.png…]()
