### ISSUE TITLE
Generate site names using Coolname

### ISSUE THREAD

**Issue by mkolar** [pypeclub/pype#1173]
We need to be generating unique IDs for the sync site in pype 3.0, however we'd like to avoid using UUID and similar approaches and these IDs might need to be re-typed, spoken and are generally user facing on occasion. 

After multiple discussions we settled on using https://github.com/alexanderlukanin13/coolname for this.

Using a 3 word combinations should be easy enough to remember, recognize and work with in general, while getting us over 100 000 000 unique options from the default dictionary. More than enough for our wildest needs (especially if we consider them only per studio). 

The idea is well explained on Asana blog https://blog.asana.com/2011/09/6-sad-squid-snuggle-softly/

Additional a bit of laugh never hurts, who doesn't want to have a site identifying itself as `fantastic-acousting-whale` or `valiant-rook-of-contentment`

**Comment by mkolar** [comment]
I'm actually wondering if 2 words might be enough. 10 000 variations is not a whole lot, but again. within a single studio? unlikely.

**Comment by tokejepsen** [comment]
Not sure I get where and how the unique IDs are used?

Guessing it not per file?

**Comment by mkolar** [comment]
It's per Pype installation. Every artist and every machine that is running pype and will be used for synchronising files will get an ID like this.

So not massive number of them.

**Comment by mkolar** [comment]
If a studio has 50 artists and a massive farm of 200 render nodes, even that only generates 250 ids.

**Comment by mkolar** [comment]
Until a crunch time panic causes someone to spawn 100 000 000 AWS instances for rendering. I think we'll be fine.  :D
