### ISSUE TITLE
asset switcher efficiency

### ISSUE THREAD

**Issue by iLLiCiTiT** [pypeclub/pype#125]
Asset switcher require to efficiency refactor there are multiple calls to database.

**Comment by iLLiCiTiT** [comment]
Asset switcher can't solve master versions

**Comment by iLLiCiTiT** [comment]
Asset switcher can't handle missing documents or archived documents.

**Comment by iLLiCiTiT** [comment]
LODs behaviour is strange. `<without LOD>` in Lods combobox is useless.
![image](https://user-images.githubusercontent.com/43494761/81584179-b5190900-93b2-11ea-8fc5-dd1556d386f5.png)

**Comment by mkolar** [comment]
>LODs behaviour is strange. <without LOD> in Lods combobox is useless.
yep that should just show first available
