### ISSUE TITLE
Doubled site if active and remote are set to the same

### ISSUE THREAD

**Issue by mkolar** [pypeclub/pype#1290]
If artist uses the same site for both active and remote one, for example, both set to `studio` this location will get doubled on the representation. Down the line it then confuses GUIs, by showing 0% availability

![image](https://user-images.githubusercontent.com/3333008/114064137-a0324780-9899-11eb-8bd2-b0842a8182ab.png)

![image](https://user-images.githubusercontent.com/3333008/114064187-a9231900-9899-11eb-99ea-5bb10fda0e99.png)

**Comment by kalisp** [comment]
Fixed in `feature/1121-site-sync-add-site-information-and-buttons-to-loader_op` branch
