### ISSUE TITLE
Sync Queue GUI issues

### ISSUE THREAD

**Issue by mkolar** [pypeclub/pype#1294]
- [x] we should rename the GUI to **`Sync Queue`** to better reflect what it does

- [x] Let's change the status sorting to `In Progress` , `Queued`, `Failed`... the rest as is
- [x] default column widths are a bit annoying and have to be expanded every time 
![image](https://user-images.githubusercontent.com/3333008/114066077-9a3d6600-989b-11eb-90b5-2c822f676e5c.png)

- [x] This should say `Re-sync Active Site` and `Re-sync Remote Site`
![image](https://user-images.githubusercontent.com/3333008/114066649-3e271180-989c-11eb-864c-c1b944ba88f2.png)

- [ ] This should maybe say `Open in explorer`, It's probably enough to imply it means active site
![image](https://user-images.githubusercontent.com/3333008/114066790-644cb180-989c-11eb-9c37-fa1d0c9a8487.png)

- [x] To make it clear, let's join the date columns with the site icons.
- [x] also when Site has failed, we should clearly mark it. Colour or similar would work .
![image](https://user-images.githubusercontent.com/3333008/114083522-5f452d80-98af-11eb-9856-cf692ef2571d.png)

**Comment by kalisp** [comment]
That 'Open in Explorer' is there for cases studio <> local , in that case you should have access to both, studio and local versions.

**Comment by kalisp** [comment]
Pushed implemented changes
