### ISSUE TITLE
Use avalon tools outside of avalon's singleton context.

### ISSUE THREAD

**Issue by iLLiCiTiT** [pypeclub/pype#134]
Avalon context is now implemented in very singleton way and is not possible to call most of methods/functions without setting context in global variable which is not safe if multiple threads want to use these methods with different contexts.

Same with avalon tools. It is necessary to be able to use any avalon Tool only with context filled with the arguments or other way.

**Comment by iLLiCiTiT** [comment]
## On Hold
This issue would require to rewrite avalon-core and pyblish-base, then modify pype to be able to work with modified repositories.

## Why:
Both avalon-core and pyblish-base are actually singleton based in core implementation, all registered host, root, plugins, plugins path, context, etc... are held inside the module itself, with this is not possible to be able hold 2 different contexts. To do this would require to wrap current implementation into one class with own pipeline context.

**Comment by mkolar** [comment]
I'm closing the issue. This architecture is so intertwined with avalon, that it would require too much of a re-write to be worth it.
