### ISSUE TITLE
Avalon Mongo Connection split

### ISSUE THREAD

**Issue by iLLiCiTiT** [pypeclub/pype#136]
It is required to split avalon's mongo connection out of avalon's Session! This is just practical issue, now we have `io_nonsingleton` but each time new object is created, new connection to mongo is created so one running pype may have 16 connections to mongo. This is too much for single application accessing the same data but from different table (collection).

Idea of implemetation:
1.) Singleton object caring only about connecting to Mongo DB. Let's call it `AvalonMongoDB`
2.) Class `AvalonMongoConnection` which can hold context. Let's call the context atttribute `Session` for backwards comaptibility.
3.) `AvalonMongoDB` should be used as current `avalon.io` so by default has one stored object of `AvalonMongoConnection` it's `Session` is filled with environments and is stored to `avalon.api`.
4.) At the same time `AvalonMongoDB` should have method like `get_mongo_connection` which returns new `AvalonMongoConnection` object with unfilled `Session`.
5.) This connection has it's own context but is using the same connection. Methods like `install` and `uninstall` remains but for `AvalonMongoConnection` the `install` method just mean to trigger creating of connection to mongo in `AvalonMongoDB` at the same time `AvalonMongoDB` should store booleans about each instance if the instance is marked as "installed". If all instances are not "installed" then connection to mongo is lost.

Let me know what you think, what names for `AvalonMongoDB` and `AvalonMongoConnection` would be best and what would you change. With this approach avalon is backwards compatible just adds new feature.

**Comment by mkolar** [comment]
Let's describe in more detail why we think this is needed and create an issue in avalon-core, as this would heavily affect it.

**Comment by iLLiCiTiT** [comment]
This is currently required only because we want use Avalon's mongo connection in pype (in many places all with different context) so it's more our issue which may not be accepted.

But if we'll speak about using avalon tools in premiere, photoshop or other hosts without python, and have ability to have multiple opened those hosts at the same time, with one running listening server(rest api, websockets, etc.), then having this feature is one of first steps. I'll think about it.

**Comment by iLLiCiTiT** [comment]
Implemented with https://github.com/pypeclub/avalon-core/pull/187
