### ISSUE TITLE
Application Manager

### ISSUE THREAD

**Issue by iLLiCiTiT** [pypeclub/pype#152]
Convert avalon's launching system to something like Application Manager and give ability in avalon to register custom Application Manager with custom launching system.

**Comment by antirotor** [comment]
Do you have any preview about how that shoud work? No matter how this will end up, I vote for one feature that could save us few files in *pypeclub/pype-config*:

### Auto app discovery

Most of the time I feel that applications are installed in their default locations. We could automatically search those locations and add applications and their variants to Pype at runtime.

**Comment by iLLiCiTiT** [comment]
When there is possiblity to register custom ApplicationManager we can do anything...

My sketch of implementation are 3 Abstract classes `ApplicationManager`, `Application` and `Tool`.
## <Application> methods/attributes:
- `name` - should be used as ID
- `parent` - pointer to manager
- `label` - Label
- `icon` (optional) - for avalon launcher
- `launch(self, args=None, env=None, cwd=None, **kwargs)` launches application
    - Not sure about default kwargs (args, env, cwd) because it may be possible that you want to enter just context and everything else should be done by implementation itself.

I think these are required. Others are in mind for custom implementation: `hooks` (prelaunch, postlaunch hooks, `default_env` e.g. PYBLISH_GUI: pyblish-lite), `data` additional data like ftrack icon etc.

## <Tool> method/attributes:
- `name` - unified name
- `envs` - environments

Is there anything more about tools?

## <Manager> with methods:
- `applications` - List `[<app name1>, ...]` or dictionary `{<app name1>: <Application object>, ...}` of available apps?
- `tools` - same as applications but with <Tool object>s
- `get_application(self, app_name)` - Should return `Application object` of app_name. If applications is dict than does not make so much sence?
- `launch(app_name, *args, **kwargs)` - Wrapper for launching application.

With this, I think, it should be possible to have current avalon's setup and kept door opened for our changes.
I am ready for criticism :)

**Comment by tokejepsen** [comment]
May have the wrong end of this bit this might serve as inspiration as well: https://github.com/getavalon/docker/pull/52/files

**Comment by antirotor** [comment]
I like the idea of application specific classes. When they are needed (mostly all should be handled by default `Application` class, they could be loaded as plugins. So when I need to add some new mysterious application that doesn't behave the same as others, I'll put to `applicationManager/plugins` (or whatever) file `mysterious_app.py` and it would define location and launching behavior for that. Of course this can be handled by hook system as well, but maybe both of those concepts can live along together.

**Comment by iLLiCiTiT** [comment]
The idea is that you have to implement your `ApplicationManager` with those methods and how the manager will load applications or tools it's up to you. You can keep tomls, you can change that to jsons, you can have python file definitions you can have predefined paths where to look for executables or all combination of all these, so you can look for executables on drive and then check path defined in your json, filter tools by host name and so on, load environments for specific project from DB of from project presets, you can keep running instances in list so you know if they ended... With this abstraction you can do what you need and is not force one access. Discovery, way of launching, setting environments for `Application`s and `Tool`s is up to manager's implementation.

**Comment by antirotor** [comment]
Sure thing, but we need one `ApplicationManager` implementations ourselves ;)
