### ISSUE TITLE
Publishing: better error reporting

### ISSUE THREAD

**Issue by antirotor** [pypeclub/pype#162]
## Better and more user-friendly error reporting

Sometime error popping up from Pype are quite intimidating. Errors on user end ending up as scary Python tracebacks are not helping end-user to underestand that he made some mistake in scene and this redirect him to our support with often trivial issues.

Better error reporting and documentation can lead to overall better feeling coming from working with Pype.

## GUI changes

As a first step we can modify main GUI user usually encounter errors - publishing. This is mockup how error coming from validator can be presented to user:

![better_errors](https://user-images.githubusercontent.com/33513211/82448417-fba0ee80-9aa9-11ea-99f5-38075dfe3093.png)

## Technical aspects

This will require changes is publishing plugins, more `try / except` instead of asserts. We can create our own custom exception that can handle links to web documentation and markdown formatted help text (possibly taken from plugin docstrings itself as is done now for plugin description).

**Comment by tokejepsen** [comment]
Instead of `try/except` why not custom assert methods?
Miniman change to the code needed.

**Comment by antirotor** [comment]
> Instead of `try/except` why not custom assert methods?
> Miniman change to the code needed.

True but we use mixed asserts and exceptions. This would still need to be unified.

**Comment by antirotor** [comment]
I'll use this issue to add scary error messages that we need to change. First:

**Collect Version**
```
int() argument must be a string or a number, not 'NoneType'
```
This happens when running pyblish on blank scene in maya or scene without version string in its name.

**Comment by antirotor** [comment]
This is another example. Failing validator on scene settings. You really need to decipher what's going on and I suppose it is scary for artists.

![MRV5k3TZaY_A74qDUi0qs7AFwBGck4Te8Q](https://user-images.githubusercontent.com/33513211/99240657-1821a780-27fd-11eb-8bfb-50b58667f536.png)
