### ISSUE TITLE
exctract review letter_box not correct when wider

### ISSUE THREAD

**Issue by jezscha** [pypeclub/pype#167]
At the moment we are not expecting case where input format would be wider then required letter_box ratio `drawbox=0:0:iw:round((ih-(iw*(1/{letter_box})))/2)` is the basic ffmpeg expression for one from couple drawboxes (letter_box rectanger). we have to identify if the input ratio is wider then letter_box number and swap from `ih` drawbox calculation to `iw`. 

This is edge case scenario but it can happen.

**Comment by iLLiCiTiT** [comment]
I think this is already solved in current version of ExtractReview
