### ISSUE TITLE
pyblish-lite: Duplicated intent due to project overrides

### ISSUE THREAD

**Issue by iLLiCiTiT** [pypeclub/pype#173]
Intent values are duplicated when presets for intents are set in project overrides. And probably when has differrent default. Must be tested!
![image](https://user-images.githubusercontent.com/43494761/82894382-c5a0b600-9f52-11ea-9436-6ed7ca9b46c6.png)

**Comment by iLLiCiTiT** [comment]
I know how this can be fixed but that would add more complexity to the presets at the same time. I would not do that as intents are not meant to be overriden. With config gui system this won't be possible as they will be system configuration which are not overridable, and I'm not sure if anybody is using them now?

**Comment by mkolar** [comment]
This won't be need anymore thanks to new system settings.
