### ISSUE TITLE
3.0: Move most code from pype-setup/pypeapp to pype

### ISSUE THREAD

**Issue by iLLiCiTiT** [pypeclub/pype#176]
Move almost each file from pype-setup/pypeapp to pype/lib. Like anatomy, config, log, etc.

**Comment by mkolar** [comment]
Just a note that this is related to major refactoring of the codebase as preparation for easier deployment and remote installation.

**Comment by iLLiCiTiT** [comment]
Now requires to modify pype-setup basic implementation to not have cross used lib callbacks. At this time it is not possible to remove anything from `pypeapp/lib`.
