### ISSUE TITLE
Pypeapp Logging terminal print doubled

### ISSUE THREAD

**Issue by jezscha** [pypeclub/pype#177]
Problem:
On some occasions prints in terminal coming from pypeapp logger are doubled. Causing no harm to running operations but messing up terminal readability.

Noticed when:
1. running Resolve launcher with used prelaunch hook
   a. hook is printing once and starting resolve.lib.setup()
   b. resolve.lib is using `log = Logger().get_logger(__name__, "resolve")`. Duplicated printing is starting.
   c. if all processes from resolve.lib ends the single print is back again.

**Comment by iLLiCiTiT** [comment]
PR https://github.com/pypeclub/pype/pull/866 will maybe fix this issue
