### ISSUE TITLE
3.0: Config cleanup

### ISSUE THREAD

**Issue by iLLiCiTiT** [pypeclub/pype#179]
Presets need few changes:
1.) Remove presets which are not changeable (e.g. file extensions for djv should be hardcoded in code because client should never change that and we will never change that - or not?)
2.) Then split presets in 2 parts: "presets" overridable in project configs and something (temporarily called) "configurations" which should contain studio configurations like which modules should be used, which ftrack actions will be registered and so on

**Comment by iLLiCiTiT** [comment]
I think already solved with settings

**Comment by mkolar** [comment]
indeed
