### ISSUE TITLE
Store task types

### ISSUE THREAD

**Issue by iLLiCiTiT** [pypeclub/pype#180]
# Issue
Now we have only list of strings representing task names on asset, and available tasks on project (not used in our setup now) which creates limits.

# Suggested solution
We should have defined task types on project, for possible future usage and maybe for defying task short names.
### Asset's tasks now:
```
{
    "data": {
         "tasks": ["task1", "task2", ...]
        ...
    }
    ...
}
```

### How it may look:
```
{
    "data": {
         "tasks": {
            "task1": "task_type1",
            "task2": "task_type2",
            "task3": "task_type1"
        }
        ...
    }
    ...
}
```
With this approach it should be easy to track if task name is duplicated or not.

## Possible problems
Backwards compatibility in templates. This change requires to use `{task[name]}` instead of `{task}`. I see few possible solutions:
1.) Keep old projects as before. ->This means more complicated synchronization in sync to avalon.
2.) Update old projects to match new template. -> Should mean just to update templates in anatomy, since representation has their template and data in their context they should be affected if only `{task[name]}` will be allowed to use on that projects.
3.) Implement check in Anatomy templates to use `{task[name]}` if `{task}` is in template. -> This seems to be easiest.

**Comment by mkolar** [comment]
Let's make this ticket on https://github.com/getavalon/core it's something that needs to be discussed broadly. But besides that I agree 100% and would vote for option 3

**Comment by iLLiCiTiT** [comment]
Didn't realize, but this way we can add only type, but it would be nice to have also other task type related data (like short name). This should be on project with types definitions itself. Issue is that current upstream version of storing task (with types and icons, etc.) is by list.

Project Document has in config `"tasks"`:
```
Project document: {
    "config": {
         "tasks": [
            {"name": "model", "icon": "fa.icon name"},
            {"name": "render"},
            ...
        ]
        ...
    }
    ...
}
```
I see 2 potential problems:
1.) This way it doesn't make sence to store task name into project configuration as is possible to have multiple tasks with same type but different name.
2.) It's more complicated to handle duplicated types.

I suggest to change project's task info into dictionary where key will represent `"task type"` and it's value is another dictionary with additional data for the task type.
```
Project document: {
    "config": {
        "tasks": {
            "animation": {
                "short": "anim",
                "default_name": "Animation",
                "icon": "fa.icon name"
            },
            "art": {}
            ...
        }
        ...
    }
    ...
}
```
This way we avoid duplicated types and can store as many additional info per task type as we like to.

With combination of asset's task definitions
```
{
    "data": {
         "tasks": {
            "Art": "art",
            "Animation 3D": "animation",
            "Animation 2D": "animation"
        }
        ...
    }
    ...
}
```
### Pros
- avoid duplicated task types and names
- able to know what's short name, icon,... per task type

### Cons
- If anyone would need to have different short name for `Animation 3d` and `Animation 2d` it would require to have 2 different task types
