### ISSUE TITLE
Create Abstract class for module

### ISSUE THREAD

**Issue by iLLiCiTiT** [pypeclub/pype#187]
There should be abstract class used as base class for modules, which defines methods that must or may be implemented...

**Comment by tokejepsen** [comment]
For modules or hosts?

**Comment by iLLiCiTiT** [comment]
I though pype modules, but you're right. It would be great to have abstract class for host because it is not much clear which methods are required and are optional for host. That's more avalon issue...

**Comment by mkolar** [comment]
this has been implemented when we finished the module manager in 3.0
