### ISSUE TITLE
Define studio specific configurations

### ISSUE THREAD

**Issue by iLLiCiTiT** [pypeclub/pype#218]
Pype 3 feature

## Intro
We have to decide how presets will be split in pype-config. Found out there are 3 types of presets currently:
1.) presets which should not be in pype-config at all because are not configurable by any client else everything will break
2.) presets which are studio specific
3.) and presets which are studio and project specific

## What should happen
- Presets from point 1.) should be moved to code (other issue to decide which)
- Presets from point 2.) should not be in presets (I think) to be 100% sure they are not accidentally overriden (copying whole presets folder or anything else)
- Presets from point 3.) stay as they are but reorganize them (other issue to decide how)

## Questions
- how should we call configurations from point 2.)?
    - my suggestion is `configurations` :)
    - keep in mind we can also change name and meaning of `presets` and maybe find more "fit" name
- should data for point 2.) be loaded with data from point 3.) and oposite (now we have only `get_presets`)?
    - i think it should be separate to easily see where data are coming from and avoid possible overriding keys
    - on the other side it may be messy because few keys will be in both, like ftrack will have studio specific configurations and project overridable values for sure

**Comment by mkolar** [comment]
I'll add a note of structure that came out of previous discussion on the topic
![Pype Remote _ 3 0](https://user-images.githubusercontent.com/3333008/83645956-5a3e9000-a5b3-11ea-897b-52a6c10eb1f0.jpg)

**Comment by tokejepsen** [comment]
Is `system-level` site wide?

Is `project-level` per project name?

**Comment by mkolar** [comment]
Yeah. That was prettu much what came out of the previous brainstorm that we have `system` configs (for lack of better term) and `project` configs. I'd say that they map to cases 2) and 3) of what @iLLiCiTiT has mentioned.

**Comment by mkolar** [comment]
the actual naming of the folder is up for the discussion of course.

**Comment by iLLiCiTiT** [comment]
BTW I've tried to prepare how it may look after all changes and not much remained. And Ftrack is only one who has both system and project levels.

**Comment by iLLiCiTiT** [comment]
I've made draft PR for the expected changes https://github.com/pypeclub/pype-config/pull/36

**Comment by iLLiCiTiT** [comment]
Issue probably already solved with settings?

**Comment by mkolar** [comment]
solved
