### ISSUE TITLE
Switch from master to equivalent

### ISSUE THREAD

**Issue by mkolar** [pypeclub/pype#220]
Currently we can switch any versioned asset to a master version, but to switch back artist need's to choose explicit version to switch to

We should have option to switch between master, and it's equivalent version, which doesn't always have to be the last one.

same as we have with switching to master
![image](https://user-images.githubusercontent.com/3333008/83760575-6c810280-a675-11ea-8b7c-f7f111e6e3d3.png)

![image](https://user-images.githubusercontent.com/3333008/83760681-8fabb200-a675-11ea-8983-7dcaedfe93ac.png)

**Comment by iLLiCiTiT** [comment]
Resolved with https://github.com/pypeclub/avalon-core/pull/141
