### ISSUE TITLE
Move look assigner to pype

### ISSUE THREAD

**Issue by mkolar** [pypeclub/pype#228]
**Is your feature request related to a problem? Please describe.**
We're currently using maya-look-assigner from a separate repository. However it is such integral part of the system, that in the move towards simpler management of 3.0, we should make it part of pype.

**Describe alternatives you've considered**
 It would be really great to have it part of avalon itself, however the way it works is very dependent on what exactly the look packages look like and that is defined in pype and colorbleed config.

**Comment by tokejepsen** [comment]
Would be good to separate the assigning logic from the UI, so we can script through look assignments and use it when building a workfile.
Similarly it would be good use this code to improve updating looks in the scene manager.
