### ISSUE TITLE
Move avalon-launcher functionality to pype

### ISSUE THREAD

**Issue by mkolar** [pypeclub/pype#229]
**Is your feature request related to a problem? Please describe.**
We're currently following avalon lead in using separate repository for avalon-launcher. There is a fair amount of conversation on launcher updates or changes in the upstream of avalon. https://github.com/getavalon/core/issues/409 https://github.com/getavalon/core/issues/374

Now we know the we will want to do a major overhaul to the launcher, so doesn't have to be just the backup solution for when project management is down, however until that happens, it might make sense to move it to `tools` in avalon for easier management.

**Comment by iLLiCiTiT** [comment]
The `avalon-launcher` is already replaced with another launcher tool. (https://github.com/pypeclub/pype/pull/443)
