### ISSUE TITLE
Pyblish-pype toggle instance callback

### ISSUE THREAD

**Issue by tokejepsen** [pypeclub/pype#273]
Currently pyblish-pype does not support `instanceToggled`:
```
pyblish.api.register_callback(
    "instanceToggled", on_pyblish_instance_toggled
)
```

**Comment by iLLiCiTiT** [comment]
I expect there are arguments for `on_pyblish_instance_toggled` function, do you know what they expect?

**Comment by tokejepsen** [comment]
> Do we want pluginToggled?

Havent got/seen a use case for that, so no need to add it for my sake.

**Comment by iLLiCiTiT** [comment]
I see only one possible issue: It's possible to toggle instance outside GUI (e.g. inside plugin) and I can't much catch that...
