### ISSUE TITLE
Maya: instance attributes

### ISSUE THREAD

**Issue by antirotor** [pypeclub/pype#280]
## Problem:

Maya has a bug for some time now, when adding attributes to node, they are hijacked by arnolds extra attributes. They can be found then in `Arnold -> Extra Attributes` and this is confusing. Also instance paramteres are mixed there with user custom ones adding to confusion.

## Proposal:

We could create our own node type we'll attach to instance set. Then we can create attribute templates to better describe attribute names and types.

I am not sure if it is possible to do it using some *universal template*. If not, we could create templates for each creator,

This has additional benefit of being able to describe attributes more precisely - right now avalon is naming attributes by parsing camelCase variables set by creator - so for example `frameStart` become `Frame Start`. This is ok with its simplicity but lacks user confort and ability to describe attribute more or add inline help for artist there.

As I've never worked with attribute templates in Maya myself and I am not sure that they can be create dynamically, this would add more complexity to code but it will enhance user experience.

**Comment by mkolar** [comment]
Considering we're planning to re-do the whole UX of publishing and working with the attributes, I'd say this won't be needed.

**Comment by antirotor** [comment]
True, with those changes implemented, it won't be necessary.
