### ISSUE TITLE
Expose warnings to user in pyblish-pype

### ISSUE THREAD

**Issue by tokejepsen** [pypeclub/pype#291]
When there is a warning log on a plugin, it would be great to expose this to the user as a yellow color indication.

**Comment by iLLiCiTiT** [comment]
That's already implemented but color is orange.

**Comment by tokejepsen** [comment]
Didnt seem to work with this https://github.com/pypeclub/pype/pull/293
Using `self.log.warning` in collection stage.

**Comment by iLLiCiTiT** [comment]
> Didnt seem to work with this #293

Will investigate as soon as possible.
