### ISSUE TITLE
move maya look assigner to pype menu

### ISSUE THREAD

**Issue by mkolar** [pypeclub/pype#292]
Look assigner is currently only accesible via icon on the tool panel on the bottom left side of the maya windows. We should add it to main tools in the main menu.

**Comment by mkolar** [comment]
maybe a good variant would be to make this a submodule instead.

**Comment by kalisp** [comment]
Took a stab at this, not sure of "make this a submodule instead". Does it mean to consume separate repo and move it to modules in pype?

**Comment by kalisp** [comment]
Links to https://github.com/pypeclub/pype/issues/228
