### ISSUE TITLE
Python detection

### ISSUE THREAD

**Issue by antirotor** [pypeclub/pype#314]
## Problem

On Windows after update 1903 there is possibility for python to be hijacked by Windows Store *helpers* located in

```
C:\Users\Username\AppData\Local\Microsoft\WindowsApps
```
if this path is in `PATH`.

This calls maybe for more sensible approach for python detection, like parsing `PATH` or something.

**Comment by mkolar** [comment]
This is luckily irrelevant in 3.0. closing happily.
