### ISSUE TITLE
Clean Up Baked Movie

### ISSUE THREAD

**Issue by tokejepsen** [pypeclub/pype#369]
When cleaning up in Nuke, the baked movie is not deleted.

**Comment by jezscha** [comment]
this could be solved by this #377

**Comment by tokejepsen** [comment]
> this could be solved by this #377

Just testing, and it doesnt

**Comment by jezscha** [comment]
> > this could be solved by this #377
> 
> Just testing, and it doesnt

did you add regex pattern to presets?

**Comment by tokejepsen** [comment]
> did you add regex pattern to presets?

I didnt. Could find any documentation about that on the PR and the PR is not dependent on any other PRs, so its hard to figure this out without a deep dive into the code. What do I need to do?

**Comment by tokejepsen** [comment]
@jezscha do you have any example of using an regex pattern?

**Comment by jezscha** [comment]
> @jezscha do you have any example of using an regex pattern?

sorry I am back on. I was adding this to client and it was working. It is searching in `instance.data.get("transfers")` which is `[(src,dst),]` created in integrate_new.py, so it should be capable to erase anything in rendering folder. Try to find the correct regex patern here https://regexr.com/ (i love this tool!)

```json
{
"CleanUp":{
        "paterns": [
            "^.*_renderAnimationMain.*.jpg"
        ]
    }
}
```

**Comment by tokejepsen** [comment]
Thanks @jezscha
Ended up with `.+.baked.mov`
