### ISSUE TITLE
Extract review a representation name with `*_burnin`

### ISSUE THREAD

**Issue by jezscha** [pypeclub/pype#388]
**Describe the bug**
Some hosts (maya) are creating published represetation names with `_burnin` and it is creating inconsistency in Loader plugin representation filters.

**Expected behavior**
All representations across pipeline should have the same name defined from name of Exctract Review preset output name.

**Screenshots**
![image](https://user-images.githubusercontent.com/40640033/88649421-215cfc00-d0c8-11ea-9930-3a45cbc4afc1.png)

**Comment by jezscha** [comment]
this issue is caused by code from `extract_burnin.py:198-202`

```python 
# Update name and outputName to be able have multiple outputs
# Join previous "outputName" with filename suffix
new_name = "_".join([new_repre["outputName"], filename_suffix])
new_repre["name"] = new_name
new_repre["outputName"] = new_name
```

@iLLiCiTiT do you thing this could be removed? I personally thing it is unlikely more burn-in variants will be used. what do you thing @mkolar or @antirotor ?

**Comment by iLLiCiTiT** [comment]
I don't have opinion about that.

I think it was added because we wanted to have ability to create more than one burnin output from same source. With this it would require to rewrite the code and disable this ability...
