### ISSUE TITLE
Ftrack thumbnail propagation from version ignore audioMain

### ISSUE THREAD

**Issue by jezscha** [pypeclub/pype#395]
**Is your feature request related to a problem? Please describe.**
At the moment during publishing two versions to ftrack - first video review and second audioMain - event server is propagating the last published (audioMain) and only static thumbnail is shown instead of nice video preview 

**Describe the solution you'd like**
pype-config presets could have white or black list for responsible propagation event 

![image](https://user-images.githubusercontent.com/40640033/88690362-e1177100-d0fb-11ea-812a-57d4425691dc.png)

**Comment by mkolar** [comment]
this has been sorted in 3.0 already by allowing filter on asset type
