### ISSUE TITLE
Delete Old Versions from Library

### ISSUE THREAD

**Issue by tokejepsen** [pypeclub/pype#396]
Currently the "delete old versions" actions is dependent on Ftrack, but most files are not registered in Ftrack.

It would be better to have an action in the Library loader to do this logic.

**Comment by tokejepsen** [comment]
We could use Loader options, but noticed its not implemented for the Library Loader;
https://github.com/getavalon/core/pull/482

**Comment by mkolar** [comment]
resolved by https://github.com/pypeclub/pype/pull/1012
