### ISSUE TITLE
Render farm vendor switcher

### ISSUE THREAD

**Issue by jezscha** [pypeclub/pype#449]
**Is your feature request related to a problem? Please describe.**
At the moment we are defining either Deadline or Master rendering by deploy.json. It will add particular environment variable into environment . In case there is no `DEADLINE_REST_URL` in the environment we are adding `http://localhost:8082` and trying to submit. Only way to disable deadline workflow is to switch off plugins in presets. 

**Describe the solution you'd like**
We could also add `PYPE_RFARM_VENDOR` variable to environment holding either `deadline` ,  `muster` or `opencue` value. And in plugins we could be checking this variable and activate particular workflow

**Comment by mkolar** [comment]
I agree that choosing a render manager should be a switch in the settings. This is dependent on finishing the settings GUI, which will make the whole thing a lot easier.

**Comment by mkolar** [comment]
This is depends on #604

**Comment by mkolar** [comment]
this has been solve by implementing module manager in 3.0
