### ISSUE TITLE
burnins presets hosts related

### ISSUE THREAD

**Issue by mkolar** [pypeclub/pype#48]
<p>I had noticed some burnins are probably different in Maya then in Nuke or perhaps it is different per Task. I suggest to use anatomy idea and expand it to something like this:</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-json">burnins:
    opacity: 1
    x_offset: 5
    y_offset: 5
    bg_padding: 5
    bg_opacity: 0.5
    font_size: 42
    top_left: <span class="code-quote">"{version:0>4}"</span>
    top_center: <span class="code-quote">"{intent}"</span>
    top_right: <span class="code-quote">"{project[code]}_{asset}_{subset}_v{version:0>3}"</span>
    bottom_left: ""
    bottom_center: <span class="code-quote">"{start_frame}-{current_frame}-{end_frame}"</span>
    bottom_right: <span class="code-quote">"{username}"</span>
    nuke (or compositing):
top_center: <span class="code-quote">"{intent}: {comment}"</span>
bottom_center: <span class="code-quote">"{slate_start_frame}-{current_frame}-{end_frame}"</span>
    maya (or layout):
top_center: <span class="code-quote">"{intent}: {comment}"</span>
bottom_center: <span class="code-quote">"{start_frame}-{current_frame}-{end_frame}"</span>
bottom_left: <span class="code-quote">"{focal_length}"</span>
</pre>
</div></div>

<i>[PYPE-660] created by jakub</i>

**Comment by iLLiCiTiT** [comment]
Implemented in https://github.com/pypeclub/pype/pull/103
