### ISSUE TITLE
dependency security alert !

### ISSUE THREAD

**Issue by jezscha** [pypeclub/pype#484]
**Describe the bug**
github is pointing at pype-setup repository with dependency security risk

![image](https://user-images.githubusercontent.com/40640033/91181092-cdeec580-e6e8-11ea-881c-2a0ffeefc0d2.png)

according to @iLLiCiTiT we could perhaps update versions of modules so it could reduce the security.

**Comment by mkolar** [comment]
These happen pretty much every month. We updated them as they come. Always needs to be tested to compatibility though. I'll close this, as it is not a bug. just a continuous maintenance, that is done roughly once a month anyway with releases
