### ISSUE TITLE
Harmony websocket server

### ISSUE THREAD

**Issue by jezscha** [pypeclub/pype#496]
**Is your feature request related to a problem? Please describe.**
integrate Harmony to websocket server

**Comment by mkolar** [comment]
@kalisp had a stab at this and it's proving quite difficult, maybe even impossible right now, we'll have to do more research, if it becomes higher priority. Currently it's not crucial.

**Comment by kalisp** [comment]
**Summary of current state:**
Harmony uses QtScripts which is based on Qt 4.8. That version doesn't have support for websockets. Qt own https://doc.qt.io/qt-5/qtwebsockets-index.html are present only after Qt 5.3.

I tried to hijack couple of libraries from Node.js, but they depend on features of ECMAScript v6, QtScripts is on 3.

Whole QtScript is actually obsolete and unsupported by Qt for a while :(.
(In PS current implementation works as they are using some browser js engine, so Websocket API is implemented by default and our used js library just extend that.)

**Comment by tokejepsen** [comment]
Could the communication from Python be the websocket?
Then just implement an interpreter in Harmony.

**Comment by antirotor** [comment]
This is now stabilized in pypeclub/avalon-core#211. It is still not ideal as 100% websocket server would be really cool, but with limitations of QtScript it is not worth to do it.

**Comment by mkolar** [comment]
Closing this down as it is not really needed and too much hassle for little return
