### ISSUE TITLE
Harmony: Saving heavy scenes will crash

### ISSUE THREAD

**Issue by antirotor** [pypeclub/pype#507]
## Bug

Sometimes when saving heavy scenes in Harmony, they can take 10 minutes or more to save. But avalon will timeout after just 2 minutes, saving will then crash and corrupted scene is produced.

## Solution

Either we can increase timeout in [server.py](https://github.com/pypeclub/avalon-core/blob/92c520fc7c76015b2578b66d27077ab3626df405/avalon/harmony/server.py)

https://github.com/pypeclub/avalon-core/blob/92c520fc7c76015b2578b66d27077ab3626df405/avalon/harmony/server.py#L210

or increase try count.

**Comment by mkolar** [comment]
I thing try count would be a better option in this instance.

**Comment by antirotor** [comment]
I think this is solved by pypeclub/avalon-core#188
