### ISSUE TITLE
Setting GUI features and bugs

### ISSUE THREAD

**Issue by iLLiCiTiT** [pypeclub/pype#553]
## Write down requests or bug with settings gui
- please add here what should be modified or fixed in settings tool

### Feature/Bug I know about
- ~`path-widget ` does not work at all~ - FIXED
- `dict` used as widget does not recognize that has been changed (won't save overrides until `set as override` action is triggered)
- action `"Reset to pype default"` has bad filtering - can't be shown on parent items to reset to pype defaults whole hierarchy at once
- `+` and `-` buttons does not have text in the middle of the button
- multiselection combobox has too big font size
- create model-view architecture

**Comment by iLLiCiTiT** [comment]
- `text` input should have regex validations
- `text`, `dict` and `dict-modifiable` inputs should have ability to be marked to storing as environments
- `boolean` may be able to store different values than `True`/`False` should be able to set value for True and value for False
    - USAGE: e.g. for enviornments to return `"Yes"`/`"No"` (or `"1"`/`"0"`) instead of True/False

**Comment by antirotor** [comment]
```
File "E:\projects\pype\pype-3\pype\settings\lib.py", line 14, in <module>
    STUDIO_OVERRIDES_PATH = os.environ["PYPE_PROJECT_CONFIGS"]
  File "C:\Python37\lib\os.py", line 678, in __getitem__
    raise KeyError(key) from None
KeyError: 'PYPE_PROJECT_CONFIGS'
```

This pops up for me when trying to freeze **Pype 3**.

https://github.com/pypeclub/pype/blob/ce176c2732c441c67256ce4a00918313cb36d6c5/pype/settings/lib.py#L16

This shouldn't expect this to be set and if so handle it more gracefully.

**Comment by iLLiCiTiT** [comment]
Well can't do much now, as it's not yet saving to mongo...

**Comment by antirotor** [comment]
to be more precise - it doesn't matter what value it has. Problem is that all this package level code is executed during freezing as cx_freeze is trying to find all dependencies. So code exactly like this will break it:
```python
import os

FOO = os.environ["GGGGGG"]
# this will break on KeyError as it is not set during freeze time

FOO = os.getenv("GGGGGG")
BOO = os.path.join("zzz", FOO)
# this will break too, because FOO will be None and os.path.join will fail
```
It is more safe to add all those state dependent code into constructor or function call. This package level setting of variables is dangerous.

**Comment by iLLiCiTiT** [comment]
> This package level setting of variables is dangerous.

I know but at the time of doing that it had purpose as without those variables it wasn't possible to load anything. Now it doesn't make sence at all. My point was that none of these will be used so if it's stoping you, just change it...

**Comment by mkolar** [comment]
I was converting some more settings and ran into this. It happens whenever I try to save defaults, when I'm on the project tab, tweaking plugins. 

![image](https://user-images.githubusercontent.com/3333008/98875378-68ef7400-247c-11eb-80da-6de07517c006.png)

**Comment by jezscha** [comment]
type `dict-ordered` with following saved structure would be great:

```json
{
   "dict_name": [
       ("keyName", "keyValue")
    ]
}
```

**Comment by jezscha** [comment]
type `dict` could have attribute `is-ui-only` which should serve only as UI collapsible (or not) category and will not be used as hierarchy parent in data structure.

**Comment by jezscha** [comment]
type `list` could have attribute `collapsible` and `collapsed` so when there is more items in vertical display we could collapse them for easier reading.

**Comment by kalisp** [comment]
It could be possible to remove all project overrides by right mouse click on project name
Some backdrop/splash screen could be shown when switching between projects

**Comment by mkolar** [comment]
This issue is stale now and most of the points have been addressed. I'm closing it in favour of individual issues.
