### ISSUE TITLE
Prelaunch hooks as plugins

### ISSUE THREAD

**Issue by iLLiCiTiT** [pypeclub/pype#574]
## Description
- currently it is possible to define only one prelaunch hook which is host specific which has limits
- I think the best would be to have "folder" of prelaunch hooks with similar filter system as avalon plugins has
    - each prelaunch hook would be filtered by `host name` (maya), `app name` (maya_2020) and maybe by other attributes (I have in mind other keys like `pype modules`, `platform`, etc.)
    - each prelaunch hook should have access to subprocess arguments and environments with ability to modify them
        - modification of arguments may be required for adding workfile path or for hosts like Toon Boom Harmony where we may want to launch python script first and then so we may swap path to harmony executable in args

### Notes
- Folder structure of hooks
    - because prelaunch hooks would be like plugins it seems that they may be in specific folders like publish plugins are
    - I don't think they have to be separated but don't have any argument why not
        - in case they would be in specific folders we may add them to current "plugins" folder to keep pype structure "nice"
- Should we care only about pre-launch?
    - we may call then "launch hooks" and mark them to run `before` or `after` launch
    - there are currently callbacks that have more sence to be triggered after successful launch (like timer trigger)
- This is required step to be able to have paths to app/hosts executables stored in different way than in `.bat` or `.sh`
    - main reason is Harmony which require specific launch protocol
    - other reasons are for example opening last maya workfile on start etc.

**Comment by antirotor** [comment]
Maybe this could be implemented as Observer pattern in application launcher. That object will emit 3 event - pre-launch, launch and post-launch and every plugin will register itself as observer. This is by my opinion more flexible then hook system, you can pass in event data whatever you want and expand it with easily. It is somehow similar as Pyblish has it now, but I vote for more object oriented approach.

**Comment by mkolar** [comment]
resolved by https://github.com/pypeclub/pype/pull/747
