### ISSUE TITLE
Harmony: Inefficient collection of instances

### ISSUE THREAD

**Issue by antirotor** [pypeclub/pype#578]
## Problem

In current **avalon-core** implementation every reading operation on node will result in communication between client and server.

With large number of instances those calls will be numerous. In `collect_instances` we need to iterate over all nodes in scene and if they are marked as *container*, we create instance from them. To find out if they are *containers*, we call `read()` that gets all metadata from Harmony, match node name and return result if found.

**Pseudocode**:

```python
all_scene_nodes = get_all_nodes()  # first communication with server

for node in all_scene_nodes:
    node_data = harmony.read()  # this will get all metadata from scene
```
so if you have 10 nodes in scene, there will be 10 same data transfers between  client <-> server. Harmony scenes can have hundreds or nodes.

**Comment by mkolar** [comment]
solve by refactoring harmony integration in 2.13.
