### ISSUE TITLE
Unify tray servers

### ISSUE THREAD

**Issue by mkolar** [pypeclub/pype#651]
We have multiple small services currently running from tray. With recent implementation of websocket server, it seems that we can unify all or most of these into just one. 

Rest API - currently only serves static images to ftrack actions, this could be handled by the websocket server
Adobe communicator - not used at all as all adobe products are being switched to websockets. Can be deleted

There might be a problem with communication with the websockets from hosts that only support python2 like maya and nuke. For that purpose we can temporarily leave in a service that will act as a translator between simple requests to our websocket server running in the tray. This should be deprecated once we get rid of python2 for good (considering how keen Foundry is on switching nuke to py3, it might be around the year 2055)

A more robust and unified server in the tray should open paths for various other features dependent on it, like automatic timer switching based on context changes. #21

**Comment by karmakat** [comment]
@mkolar you might want to look into Pyro to communicate between interpreters with shared objects or kicking off methods from the specific interpreter in a dcc to the pype virtual env. I've had a lot of success with it in the past with Ironpython and vanilla python.

**Comment by iLLiCiTiT** [comment]
## Required steps
1.) Current Websocket server implementation from Websocket module add to avalon tools as websocket server for non python hosts, each host implementation would have own handlers (stubs) for the tool.
- Expected result: Host implementation won't use pype's server from pype's module.

2.) Rename Websocket module to Webserver module as it can handle more than websocket protocol. Remove host implementation specific parts from server and add ability to register route handlers from other modules.

3.) Find/Implement Rest api module for `aiohttp` and prepare interface for modules to easily register handlers and routes.

4.) Convert current rest api handlers to new interface.

5.) Remove Rest api module.

**Comment by iLLiCiTiT** [comment]
Resolved with https://github.com/pypeclub/pype/pull/1119
