### ISSUE TITLE
3.0 lib refactor

### ISSUE THREAD

**Issue by mkolar** [pypeclub/pype#664]
To move with pype 3.0, we need to refactor `lib.py` which is a mishmash of functions into a clean testable code inside a new lib python module.

The agreed plan is to split it into individual tasks. Everyone takes functions they wrote originally, judges where it needs to go, refactors, writes tests, if time allows. PRs with individual functions of groups of functions after refactor, should be made into `feature/664-3-0-lib-refactor ` branch. Once everything is pulling into it, we'll merge into develop. 

@kalisp will be reviewing smaller PRs to ensure consistency of code style, docstrings and general approach.

**Comment by jezscha** [comment]
Just to clarify this: are we suppose to branch from `feature/664-3-0-lib-refactor` and then after create PR with target to `Branch feature/664-3-0-lib-refactor created!` back?

**Comment by kalisp** [comment]
Yes, I would think so.

**Comment by kalisp** [comment]
Link to list of references https://docs.google.com/spreadsheets/d/17w3czPixTYYyeXoSAxlGTtoBQMbffpUAyTysiehE0MU/edit?usp=sharing
