### ISSUE TITLE
Photoshop uhiding hidden layers

### ISSUE THREAD

**Issue by mkolar** [pypeclub/pype#688]
<div> Freshdesk Ticket ID: <a href="https://pype.freshdesk.com/a/tickets/346">346</a></div>
                       <div> Freshdesk Ticket Agent: Milan Kolar</div>
                       <div> Freshdesk Ticket Agent Email: milan@pype.club</div>
                       <div> Ticket Priority: Low</div>
                       <div> Freshdesk Ticket Description: </div><div dir="ltr">
<div>hidden layers are being unhidden and show in publish . this seems like a bug </div>
</div>

**Comment by mkolar** [comment]
<div>Agent Milan Kolar linked Freshdesk ticket <a href="https://pype.freshdesk.com/a/tickets/346">346</a> for this issue.</div>

**Comment by mkolar** [comment]
Validated and this really is a problem. When publishing, the final result doesn't respect the hidden/unhidden status of a layer.

YOu can see in the image, that the original FG group has the red layer hidden, but in the loaded published version. the red line is turned on and exported.

![image](https://user-images.githubusercontent.com/3333008/98239306-040db880-1f68-11eb-851a-205230513a8c.png)

**Comment by kalisp** [comment]
Only 692 needs to be merged to solve and close this issue.
