### ISSUE TITLE
nk mask workflow

### ISSUE THREAD

**Issue by mkolar** [pypeclub/pype#69]
<ul>
	<li>add property to node > tick box <tt>reviewable</tt> this trigger families <tt>ftrack</tt></li>
	<li>add mask creator plugin</li>
	<li>add additional pre-nodes with shuffle and change channel to rgba</li>
	<li>add publish plugin CollectMasks separately after CollectWrite</li>
	<li>add mask plugin to Loader - create Read and shuffle to add into channels with subset name of the</li>
</ul>

<i>[PYPE-64] created by jakub</i>

**Comment by mkolar** [comment]
I feel this is a bit too niche considering it has been requested only once and was easily done with current tools even without a specific workflow implementation

@jezscha do you think this is still needed?

**Comment by jezscha** [comment]
@mkolar dont thing so. Nobody asked for it.

**Comment by mkolar** [comment]
closing as it is possible to achieve this using write family
