### ISSUE TITLE
Exception messages for user in creator tool

### ISSUE THREAD

**Issue by iLLiCiTiT** [pypeclub/pype#690]
## Description
Currently is not visually visible that Creator failed (and why). It would be nice to have message popup (same as loader has) that would show and error message and traceback. We should also define exception (e.g. `CreatorFailedException`), in case this exception is raise we should only show message, without traceback. This exception should be used for all known possible issues on User's side and describe him what's wrong and why creation did not finished. e.g. When "Use selection" is checked but user didn't select anything, in that case traceback doesn't make sence.

## Note
- similar exception should be added to loader tool where only message with traceback is shown right now

**Comment by iLLiCiTiT** [comment]
This would require to modify `create` function in `avalon.pipeline` currently it is capturing exceptions and is processing all plugins with same family.
- this function should expect Creator plugin as an arguments (like `load` function does) and do not discover them (again) on it's own + filter them by family

## Possible enhancement
- the best would be to skip this function and let whole processing on `Creator` object there is no reason why to run function in pipeline and not define `create` method in base `Creator` class

**Comment by mkolar** [comment]
implemented in 2.14
