### ISSUE TITLE
disable or fix grouping when multiple assets is selected in loader

### ISSUE THREAD

**Issue by mkolar** [pypeclub/pype#73]
<i>[PYPE-542] created by jakubtrllo</i>

**Comment by mkolar** [comment]
@iLLiCiTiT do you know if this is still happening?

**Comment by iLLiCiTiT** [comment]
Not really sure what was wrong?

**Comment by mkolar** [comment]
that's what I though. reported ages ago without much info even on jira

**Comment by mkolar** [comment]
closing.
