### ISSUE TITLE
Summary issue for testing of 3.0

### ISSUE THREAD

**Issue by kalisp** [pypeclub/pype#799]
This issue should be an 'umbrella' for gathering issues and observations learned during testing of 3.0.

**Comment by kalisp** [comment]
> "--debug" should 'set PYPE_DEBUG=3'

**Comment by kalisp** [comment]
Publishing in deadline doesn't work.
`publish_filesequence.py` ln 48 is one level too deep (different position in the tree in 2.0)
Then its looking for .ps1 or .bat, which is not there, probably obsolete.

**Comment by mkolar** [comment]
When running from build we're trying to get schemas from .zip which fail.
![image](https://user-images.githubusercontent.com/3333008/102826487-04abc280-43e1-11eb-8017-dfc099495182.png)

**Comment by mkolar** [comment]
We need to tell user if mongo is not found when launching frozen pype. Now it just silently crashes

**Comment by mkolar** [comment]
I'm closing this as we're now chasing only small things on this front
