### ISSUE TITLE
<pyblish-lite> allow multiline label or word wrap it

### ISSUE THREAD

**Issue by mkolar** [pypeclub/pype#86]
![a4333dd2-a2fa-4f74-a288-73dc66cfacad](https://user-images.githubusercontent.com/43494761/81147186-12a7f280-8f7a-11ea-8875-0e2b6fb357e0.png)

<i>[PYPE-750] created by jakub.trllo</i>

[PYPE-750]: https://pypeclub.atlassian.net/browse/PYPE-750

**Comment by iLLiCiTiT** [comment]
Solved with https://github.com/pypeclub/pyblish-lite/pull/52
