### ISSUE TITLE
Python executable in pype 3

### ISSUE THREAD

**Issue by iLLiCiTiT** [pypeclub/pype#924]
## Description
Pype code currently uses python executable at many places but pype 3 won't have any. These parts of code must use different approach and some will require modification. Some of them may be added to tray cli arguments some may require to use `run` argument to execute a script file.

- [x] execution of help scripts like Burnin script (https://github.com/pypeclub/pype/pull/947)
- [x] deadline publish script has to be "somehow" executed
- [x] launch of Harmony, Photoshop and AfterEffects must be converted to have a launch scipt
           - currently they use command line execution of python code which also have few other issues
           ```
           >>> python -c "import avalon.photoshop;avalon.photoshop.launch(\"executable\")"
           ```
           PRs:
           - pype https://github.com/pypeclub/pype/pull/1016
           - avalon-core https://github.com/pypeclub/avalon-core/pull/280
- [x] standalone publisher and it's publishing (https://github.com/pypeclub/pype/pull/947)
- [x] ftrack event server subprocesses (for both user and server) (https://github.com/pypeclub/pype/pull/947)
- [x] celaction `pre_celaction_register.py` line 40

### NOTES
Do we want to have a console with server in non python hosts? If yes then we should have access to both console and gui executables otherwise it won't be possible to show console.

**Comment by mkolar** [comment]
> Do we want to have a console with server in non python hosts?

I'd prefer not having it. Currently it's there just to get quicker feedback during beta testing, but its annoying to the user

**Comment by iLLiCiTiT** [comment]
Deadline publishing will be resolved with https://github.com/pypeclub/pype/pull/1058
