### ISSUE TITLE
flexible template assignment

### ISSUE THREAD

**Issue by mkolar** [pypeclub/pype#93]
**Problem.**
Currently we only differentiate between `render` and `publish` templates for publish, however introduction of multi-roots, brings the possibility to expand this radically. If a studio wants to store alembic cashes on a separate storage we can allow it with multi-roots, but we'd still need change the actual plugin that handles the cache extraction and inject `anatomy_template` to `instance.data["representation"]`. 

**Possible solution**
We should make sure that every place where we assign a particular template to an output, should be easily configurable from presets. This should be simple enough by making `template_name` a class attribute, which are automatically overridden by values from presets.

**Comment by iLLiCiTiT** [comment]
Add to IntegrateNew presets which define what anatomy template key will be used for which family representation.
