### ISSUE TITLE
Burnin can't catch prores_ks codec name

### ISSUE THREAD

**Issue by iLLiCiTiT** [pypeclub/pype#942]
## Issue
Burnin script use codec name from source for output but if input was created with `prores_ks` then codec name is only `prores`. But it seems that FFmpeg's default prores codec is `prores_aw`.

## Suggested solution
FFmpeg adds encoder and codec name to metadata tags so we can look for that there and check which was used.
- this won't solve the issue for sources not created with ffmpeg.

**Comment by mkolar** [comment]
resolved with https://github.com/pypeclub/pype/pull/960
