### ISSUE TITLE
Loader: Enum option.

### ISSUE THREAD

**Issue by tokejepsen** [pypeclub/pype#948]
**Describe the bug**

Having an `enum` option for a loader plugin produces this error;

`Skipped: "test" (__init__() takes 2 positional arguments but 3 were given)`

**To Reproduce**
1. Make this global loader;
```python
from avalon import api
from avalon.vendor import qargparse


class test(api.Loader):

    representations = ["*"]
    families = ["*"]

    options = [qargparse.Enum("sex", ["Male", "Female"])]
```
2. Load something through the Library Loader.

**Comment by iLLiCiTiT** [comment]
You have to use kwargs
```
options = [qargparse.Enum("sex", items=["Male", "Female"])]
```

**Comment by tokejepsen** [comment]
Ahhh I see. Was going from the original issue from David.
